### ISSUE TITLE
Indexing github.com/rails/rails fails

### ISSUE THREAD

**Issue by tsenart** [swistak35/orbacle#5]
**Steps to reproduce**:

```
cd /tmp
git clone git@github.com:rails/rails.git
cd rails
orbaclerun -d . index
```

**Output**:

```
I, [2018-12-14T19:53:15.898905 #43432]  INFO -- : Reading...
I, [2018-12-14T19:53:15.978461 #43432]  INFO -- : Parsing...
W, [2018-12-14T19:53:16.519625 #43432]  WARN -- : Warning: Skipped ./actionpack/test/dispatch/request_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:18.380762 #43432]  WARN -- : Warning: Skipped ./actionpack/test/controller/parameter_encoding_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:20.711887 #43432]  WARN -- : Warning: Skipped ./activesupport/test/message_verifier_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:20.888659 #43432]  WARN -- : Warning: Skipped ./activesupport/test/logger_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:20.914131 #43432]  WARN -- : Warning: Skipped ./activesupport/test/inflector_test_cases.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:21.048705 #43432]  WARN -- : Warning: Skipped ./activesupport/test/core_ext/string_ext_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:22.276906 #43432]  WARN -- : Warning: Skipped ./activesupport/test/multibyte_test_helpers.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:22.562192 #43432]  WARN -- : Warning: Skipped ./activesupport/test/message_encryptor_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:22.796347 #43432]  WARN -- : Warning: Skipped ./activesupport/test/multibyte_chars_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:23.378087 #43432]  WARN -- : Warning: Skipped ./activesupport/lib/active_support/core_ext/digest/uuid.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:32.346659 #43432]  WARN -- : Warning: Skipped ./activerecord/test/cases/adapters/postgresql/bytea_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:32.770554 #43432]  WARN -- : Warning: Skipped ./activerecord/test/cases/adapters/sqlite3/sqlite3_adapter_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:32.824835 #43432]  WARN -- : Warning: Skipped ./activerecord/test/cases/binary_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:39.395481 #43432]  WARN -- : Warning: Skipped ./actionview/test/template/template_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:42.258736 #43432]  WARN -- : Warning: Skipped ./actionmailer/test/mailers/base_mailer.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:42.399252 #43432]  WARN -- : Warning: Skipped ./actionmailer/test/base_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:43.072798 #43432]  WARN -- : Warning: Skipped ./activestorage/test/models/filename_test.rb because of Orbacle::RubyParser::SyntaxError
W, [2018-12-14T19:53:43.127565 #43432]  WARN -- : Warning: Skipped ./activestorage/test/service/shared_service_tests.rb because of Orbacle::RubyParser::SyntaxError
I, [2018-12-14T19:53:43.282151 #43432]  INFO -- : Building graph...
I, [2018-12-14T19:54:19.205790 #43432]  INFO -- : Typing...

...

/Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:570:in `block (2 levels) in connect_regular_args': undefined method `name' for #<Orbacle::GlobalTree::ArgumentsTree::Nested:0x00007fb854db32d8> (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:569:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:569:in `each_with_index'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:569:in `block in connect_regular_args'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:568:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:568:in `connect_regular_args'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:470:in `connect_actual_args_to_formal_args'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:535:in `block (2 levels) in connect_yields_to_block_lambda'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:532:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:532:in `block in connect_yields_to_block_lambda'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:530:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:530:in `connect_yields_to_block_lambda'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:510:in `handle_custom_message_send'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:452:in `handle_instance_send'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:416:in `block in handle_message_send'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/generic_type.rb:28:in `each_possible_type'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:407:in `handle_message_send'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:52:in `block in call'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:306:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/typing_service.rb:48:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/indexer.rb:137:in `block in call'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/indexer.rb:19:in `measure'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/indexer.rb:137:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/engine.rb:14:in `index'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/command_line_interface.rb:71:in `index'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/command_line_interface.rb:57:in `call_command'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/lib/orbacle/command_line_interface.rb:52:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/orbacle-0.2.1/exe/orbaclerun:6:in `<top (required)>'
	from /usr/local/bin/orbaclerun:22:in `load'
	from /usr/local/bin/orbaclerun:22:in `<main>'
```

Full output: https://gist.github.com/tsenart/0f22511d73ea1c79a833892451d177c9

**Comment by mathieujobin** [comment]
Have you tried again with latest orbacle and rails?
